#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PDL-Graphics-X
version:      0.03
version_from: X.pd
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
